version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/SqlTest"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/SqlTest.Tests"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "coverlet.collector"
      - dependency-name: "coverlet.msbuild"
      - dependency-name: "MSTest.TestAdapter"
      - dependency-name: "MSTest.TestFramework"