name: Unit tests, coveralls.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '6.0'
      - name: Run unit tests
        run: dotnet test SqlTest.Tests --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
      - name: Run invoke tests
        run: |
          cd SqlTest.Tests/bin/Release/net6.0
          sqltest --help
          sqltest --version
      - name: Run coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./SqlTest.Tests/coverage.info
        if: github.event_name != 'pull_request'