name: Unit tests, coveralls.io

on:
  push:
    branches:
      - main

jobs:
  test-on-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [net6.0, net7.0]
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: dotnet test ./SqlTest.Tests --framework ${{ matrix.framework }} --configuration Release -e CollectCoverage=true -e CoverletOutputFormat=lcov --logger "console;verbosity=normal"
      - name: Run coveralls.io
        if: ${{ matrix.framework == 'net6.0' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./SqlTest.Tests/coverage.net6.0.info
  simple-test-on-windows:
    strategy:
      matrix:
        include:
          - framework: net7.0
            image: cagrin/mssql-server-ltsc2022:2022-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull image
        run: docker pull ${{ matrix.image }}
      - name: Run simple tests
        shell: pwsh
        run: dotnet run --project SqlTest --framework ${{ matrix.framework }} -- runall --image ${{ matrix.image }} --windows-container --project Database.Tests/Ok