name: Unit tests, coveralls.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: dotnet test SqlTest.Tests --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
      - name: Run coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./SqlTest.Tests/coverage.info
        if: github.event_name != 'pull_request'
  simple-test-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run simple tests
        shell: pwsh
        run: dotnet run --project SqlTest -- runall --image cagrin/mssql-server-ltsc2022:2019-latest --windows-container --project Database.Tests/Ok