name: Unit tests, coveralls.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-on-ubuntu-net6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: cd SqlTest.Tests && dotnet test --framework net6.0 --configuration Release -e CollectCoverage=true -e CoverletOutputFormat=lcov
      - name: Run coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./SqlTest.Tests/coverage.net6.0.info
        if: github.event_name != 'pull_request'
  test-on-ubuntu-net7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: cd SqlTest.Tests && dotnet test --framework net7.0 --configuration Release -e CollectCoverage=true -e CoverletOutputFormat=lcov
  simple-test-on-windows-net6:
    runs-on: windows-latest
    env:
      IMAGE_NAME: cagrin/mssql-server-ltsc2022:2019-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull image
        run: docker pull ${{env.IMAGE_NAME}}
      - name: Run simple tests
        shell: pwsh
        run: dotnet run --project SqlTest --framework net6.0 -- runall --image ${{env.IMAGE_NAME}} --windows-container --project Database.Tests/Ok
  simple-test-on-windows-net7:
    runs-on: windows-latest
    env:
      IMAGE_NAME: cagrin/mssql-server-ltsc2022:2022-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull image
        run: docker pull ${{env.IMAGE_NAME}}
      - name: Run simple tests
        shell: pwsh
        run: dotnet run --project SqlTest --framework net7.0 -- runall --image ${{env.IMAGE_NAME}} --windows-container --project Database.Tests/Ok