name: Build, Test, coveralls.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/ci@v0.3
        with:
          runCmd: dotnet build SqlTest
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [net6.0, net7.0, net8.0]
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/ci@v0.3
        with:
          runCmd: dotnet test SqlTest.Tests --framework ${{ matrix.framework }}
  coverage:
    runs-on: ubuntu-latest
    env:
      framework: net6.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Run tests and collect coverage
        run: dotnet test SqlTest.Tests --framework ${{ env.framework }} --configuration Release -e CollectCoverage=true -e CoverletOutputFormat=lcov
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./SqlTest.Tests/coverage.${{ env.framework }}.info